#!/usr/bin/python
###############################################################################
# aping.py - Audible ping
###############################################################################
# 20200315	Chris OBrien	Initial
# 20200327	Chris OBrien	Added reverse, beep.  Better usage.
###############################################################################
# Todo: 
#	generate tone / don't use wav file (simplyaudio?)
#       set volume using -v, --volume (1-10)
#       baseline command name
#       github: installer
###############################################################################
# Prerequisites
# sudo apt-get install python
# sudo apt install python-pip
# pip install playsound


## Imports
import os
import time
import signal
import getopt, sys
from datetime import datetime
from playsound import playsound

## Variables
hostname = "8.8.4.4" # default
eeg="/usr/local/share/sounds/eeg01a.ogg"
defaulttimer = 2
reverse = False # default
class colours:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

## Functions
def signal_handler(sig, frame):
    print('Exiting!')
    sys.exit(0)
signal.signal(signal.SIGINT, signal_handler)

def usage():
  print ;
  print "Usage: \n"
  print sys.argv[0] + " <host> [options]"
  print
  print "Options:"
  print "  --help              Show help."
  print "  -h, --host          Hostname to ping.  Default is 8.8.4.4"
  print "  -d, -- delay        Set delay between pings in seconds."
  print "  -r                  Reverse ping.  (i.e. success if ping fails)"
  print "  -b, --beep          Filename of beep sound file."

## Main
try:
    opts, args = getopt.getopt(sys.argv[1:], "h:d:rb:", ["host=", "delay=", "reverse", "beep=", "help"])
except getopt.GetoptError as err:
  print(err) # will print something like "option -a not recognized"
  usage()
  sys.exit(2)
for o, a in opts:
  if o == "--help":
    usage()
    sys.exit()
  elif o in ("-h", "--host"):
    hostname = a
  elif o in ("-d", "--delay"):
    defaulttimer = int(a)
  elif o in ("-b", "--beep"):
    eeg = a
  elif o == "-r":
    reverse = True
  else:
    assert False, "unhandled option"

print "Pinging " + hostname
#if reverse:
#    print "Reverse"
#else:
#    print "Forward"

while True:
  response = os.system("ping -W1 -c 1 " + hostname + " > /dev/null 2>&1")
  # response 0 means that the ping was successful
  # response 1 means that the ping was not successful
  my_date = datetime.now()
  timeoutput = my_date.strftime('%Y%m%d%H%M%S')
  if response == 0:
    # The ping was successful
    if not reverse:
      # It's a good thing that the ping was successful
      print colours.OKGREEN + timeoutput + " Ping successful" + colours.ENDC
      playsound(eeg)
    else:
      # It's a bad thing that the ping was successful
      print colours.FAIL + timeoutput + " Ping successful" + colours.ENDC
  else:
    # The ping was not successful
    if not reverse:
      # It's a bad thing that the ping was not successful
      print colours.FAIL + timeoutput + " Ping unsuccessful" + colours.ENDC
    else:
      # It's a good thing that the ping was not successful
      print colours.OKGREEN + timeoutput + " Ping failed successfully" + colours.ENDC
      playsound(eeg)
  time.sleep(defaulttimer)
